version: "3"

tasks:
  install-requirements:
    desc: install requirements
    cmds:
      - mkdir tmp
      - task: _download-protoc
      - task: _unzip-protoc
      - mkdir -p bin
      - rm -rf bin/protoc
      - task: _locate-protoc
      - rm -rf ./tmp
      - go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
  _download-protoc:
    dir: tmp
    cmds:
      - curl -L https://github.com/protocolbuffers/protobuf/releases/download/v25.1/protoc-25.1-linux-x86_64.zip --output protoc.zip
  _unzip-protoc:
    dir: tmp
    cmds:
      - unzip ./protoc.zip -d protoc
  _locate-protoc:
    dir: tmp
    cmds:
      - mv -f ./protoc/ ../bin
  protoc:
    desc: gen protoc
    cmds:
      - bin/protoc/bin/protoc --go_out=. --go-grpc_out=require_unimplemented_servers=false:. pkg/apis/runtime/beta/*.proto
  run-server:
    cmds:
      - go run cmd/server/server.go -cmd "cni"
  run-client-detach:
    cmds:
      - go run cmd/client/client.go -cmd "detach"
  run-client-attach:
    cmds:
      - go run cmd/client/client.go -cmd "attach"
  run-client-query:
    cmds:
      - go run cmd/client/client.go -cmd "query"
  run-client-querypod:
    cmds:
      - go run cmd/client/client.go -cmd "querypod"
  run-client-status:
    cmds:
      - go run cmd/client/client.go -cmd "status"
  build-server:
    cmds:
      - CGO_ENABLED=0 go build -o ./bin cmd/server/server.go
